feat(backend): Support running behind a corporate proxy [RHIDP-2217] (#1225)
* Add the undici and global-agent packages to the backend workspace

Per [1], global-agent addresses node-fetch proxying, while undici afects
the native fetch.

[1] https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md

* Add the type definitions package for global-agent

Command used for reference: 'yarn add --dev @types/global-agent'

Otherwise, we get the following errors when building the container
images:

//:tsc: cache miss, executing 7cdd96a5dd9f08b5
//:tsc: $ tsc
//:tsc: packages/backend/src/index.ts:20:27 - error TS7016: Could not
find a declaration file for module 'global-agent'.
'/opt/app-root/src/node_modules/global-agent/dist/index.js' implicitly
//:tsc:   Try `npm i --save-dev @types/global-agent` if it exists or add
a new declaration (.d.ts) file containing `declare module
'global-agent';`
//:tsc:
//:tsc:                              ~~~~~~~~~~~~~~
//:tsc:
//:tsc:
//:tsc: Found 1 error in packages/backend/src/index.ts:20
//:tsc:
//:tsc: error Command failed with exit code 1.
//:tsc: info Visit https://yarnpkg.com/en/docs/cli/run for documentation
about this command.
//:tsc: ERROR: command finished with error: command (/opt/app-root/src/)
/tmp/yarn--1714731744742-0.9188035523240228/yarn run tsc exited (1)
//#tsc: command (/opt/app-root/src/)
/tmp/yarn--1714731744742-0.9188035523240228/yarn run tsc exited (1)

* Regen yarn.lock

* Add proxy agent to allow backend requests to support corporate proxies [1]

[1] https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md#installation

* Add support for no_proxy excludes and explicitly bootstrap global-agent with no side-effect

ref: https://gist.github.com/zicklag/1bb50db6c5138de347c224fda14286da

* Document how to run the app behind a corporate proxy

* Auto-set the GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE env var in the container image

Setting it to an empty value allows global-agent to rely on the rather
conventional HTTP(S)_PROXY and NO_PROXY env vars. [1]
Otherwise, users would need to configure both GLOBAL_AGENT_HTTP(S)_PROXY
and HTTP(S)_PROXY to make proxying work with both global-agent and other
libs.
Also, it might be a bit confusing for the user to have to set it explicitly
to an empty value.
We can set it the other way around, but users can still override it if
needed.

[1] https://github.com/gajus/global-agent#what-is-the-reason-global-agentbootstrap-does-not-use-http_proxy

* Move configureCorporateProxyAgent to a separate file

This would simplify the merging process in case of upstream changes

Co-authored-by: Gennady Azarenkov <gazarenkov@redhat.com>

* Document that proxy settings can also be specified in the operator default config

Co-authored-by: Gennady Azarenkov <gazarenkov@redhat.com>

* Add instructions for local development and testing in a separate 'docs/proxy.md' file

Co-authored-by: Corey Daley <cdaley@redhat.com>

* Document that plugin vendors have nothing to configure if they use the supported libraries for HTTP data fetching

Co-authored-by: Kim Tsao <ktsao@redhat.com>

* Apply suggestions from code review

Co-authored-by: Corey Daley <cdaley@redhat.com>

---------

Co-authored-by: Gennady Azarenkov <gazarenkov@redhat.com>
Co-authored-by: Corey Daley <cdaley@redhat.com>
Co-authored-by: Kim Tsao <ktsao@redhat.com>